/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./src/components/contextMenu.vue')['default']
    FileMenu: typeof import('./src/components/FileMenu.vue')['default']
    UButton: typeof import('./src/components/UButton.vue')['default']
    UModal: typeof import('./src/components/UModal.vue')['default']
    UniverDoc: typeof import('./src/components/UniverDoc.vue')['default']
    UniverSheet: typeof import('./src/components/UniverSheet.vue')['default']
  }
}
