/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FileMenu: typeof import('./src/components/FileMenu.vue')['default']
    HelloVue: typeof import('./src/components/hello-vue.vue')['default']
    UniverSheet: typeof import('./src/components/UniverSheet.vue')['default']
  }
}
