/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./src/components/contextMenu.vue')['default']
    FileMenu: typeof import('./src/components/FileMenu.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    UButton: typeof import('./src/components/UButton.vue')['default']
    UniverSheet: typeof import('./src/components/UniverSheet.vue')['default']
  }
}
